### ISSUE TITLE
Crashing after selecting Dxvk HUD Settings without it being on

### ISSUE THREAD

**Issue by tedzards509** [CommandMC/Rare#1]
I installed the "rare" package from AUR.
When I launch it I am able to open the "More CXVK settings" Button despite "Show Dxvk HUD" not being checked. When I select a Setting in the More DXVK settings menu, rare crashes.

**Comment by tedzards509** [comment]
The entire Console Log:

`[Utils] INFO: Found locale in system config: en
[Login] INFO: Try if you are logged in
[Core] INFO: Trying to re-use existing login session...
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
[Login] INFO: You are logged in
[Utils] INFO: Create Image dir
[Utils] INFO: Download Image for Game: Fortnite
[Utils] INFO: Download Image for Game: Oxenfree
[Utils] INFO: Download Image for Game: Oxenfree
[Utils] INFO: Download Image for Game: Rocket League®
[Utils] INFO: Download Image for Game: Slime Rancher
[Utils] INFO: Download Image for Game: Slime Rancher
[Utils] INFO: Download Image for Game: The Textorcist
[Utils] INFO: Download Image for Game: The Witness
[Utils] INFO: Download Image for Game: The Witness
[Utils] INFO: Download Image for Game: Watch Dogs 2
[Utils] INFO: Download Image for Game: Watch Dogs 2
[Utils] INFO: Found locale in system config: en
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1145, resource id: 0, major code: 18 (ChangeProperty), minor code: 0
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Rare/Components/Tabs/Settings/Dxvk.py", line 129, in change
    self.core.lgd.config[f"{self.name}.env"]["DXVK_HUD"] = ",".join(sett)
  File "/usr/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'default.env'
Aborted (core dumped)
`

**Comment by CommandMC** [comment]
So there I was, making this Repo ready for archival (since I'm working on a successor), when I see this issue. I'm sorry for only responding so late, I've not gotten any notifications about it for *some* reason.

`rare` in the AUR is not this project, see [Dummerle/Rare](https://github.com/Dummerle/Rare)
